<?php

namespace App\Services;

use App\Http\Controllers\Controller;

class RolesRoutingService extends Controller
{

    public function getRoleData($user): array
    {
        $roles = [

            'admin' => [
                'employee_index' => 'erp.admin.employees.index',
                'employee_edit' => 'erp.admin.employees.edit',
                'employee_create' => 'erp.admin.employees.create',
                'employee_search' => 'erp.admin.employees.search',
                'employee_store' => 'erp.admin.employees.store',
                'employees_update' => 'erp.admin.employees.adminUpdate',
                'employee_delete' => 'erp.admin.employees.delete',

                'messages_show_chat' => 'erp.admin.messages.showChat',
                'messages_index' => 'erp.admin.messages.index',
                'messages_update_notifications' => 'erp.admin.messages.updateNavbarNotifications',
                'messages_search_users' => 'erp.admin.messages.searchUsers',
                'messages_search'=>'erp.admin.messages.search',
                'messages_delete_chat' => 'erp.admin.messages.deleteChat',
                'messages_add_user' => 'erp.admin.messages.addUser',
                'messages_store_chat_message' => 'erp.admin.messages.storeChatMessage',
                'messages_update_message'=>'erp.admin.messages.updateMessage',
                'messages_update_chat_message'=> 'erp.admin.messages.updateChatMessage',
                'messages_delete_message' => 'erp.admin.messages.deleteMessage',
                'messages_delete_chat_message' => 'erp.admin.messages.deleteChatMessage',
                'messages_show_private_chat' => 'erp.admin.messages.showPrivatChat',
                'messages_store_private_message' => 'erp.admin.messages.storePrivatMessage',
                'messages_read_message' => 'erp.admin.messages.readMessage',
                'messages_store_chat' => 'erp.admin.messages.storeChat',
                'messages_store_message' => 'erp.admin.messages.storeMessage',
                'messages_chat_reply' => 'erp.admin.messages.chatReply',
                'messages_message_reply' => 'erp.admin.messages.messageReply',
                'messages_update_chat' => 'erp.admin.messages.updateChat',

                'articles_index' => 'erp.admin.articles.index',
                'articles_show_article' => 'erp.admin.articles.showArticle',
                'articles_store_article' => 'erp.admin.articles.storeArticle',
                'articles_add_to_favorites' => 'erp.admin.articles.addToFavorites',
                'articles_edit' => 'erp.admin.articles.edit',
                'articles_delete' => 'erp.admin.articles.delete',
                'articles_update_article' => 'erp.admin.articles.updateArticle',
                'articles_search' => 'erp.admin.articles.search',

            ],

            'manager' => [
                'leads_index' => 'erp.manager.leads.index',
                'leads_search' => 'erp.manager.leads.search',
                'leads_to_order' => 'erp.manager.leads.toOrder',
//                'leads_delete' => 'erp.manager.leads.delete',
                'leads_delete' => 'erp.manager.leads.destroy',
                'leads_update' => 'erp.manager.leads.update',
                'leads_store' => 'erp.manager.leads.store',
                'leads_delete_file' => 'erp.manager.leads.deleteFile',


                'store' => 'erp.manager.orders.store',
                'order_create' => 'erp.manager.orders.create',
                'order_edit' => 'erp.manager.orders.edit',
                'order_search' => 'erp.manager.orders.search',
                'order_index' => 'erp.manager.orders.index',
                'order_delete' => 'erp.manager.orders.delete',
                'order_cancellation' => 'erp.manager.orders.cancellation',
                'order_return' => 'erp.manager.orders.return',

                'update' => 'erp.manager.orders.update',
                'orders_addFiles' => 'erp.manager.orders.addFiles',
                'orders_deleteFile' => 'erp.manager.orders.deleteFile',
                'orders_toBankOperations' => 'erp.manager.orders.toBankOperations',
                'orders_addComment' => 'erp.manager.orders.addComment',
                'orders_to_bank_operations' => 'erp.manager.orders.toBankOperations',

                'arrears_search' => 'erp.manager.arrears.search',
                'arrears_index' => 'erp.manager.arrears.index',

                'clients_index' => 'erp.manager.clients.index',
                'clients_edit' => 'erp.manager.clients.edit',
                'clients_contact_delete' => 'erp.manager.clients.client_delete',
                'clients_store' => 'erp.manager.clients.store',
                'clients_update' => 'erp.manager.clients.update',
                'clients_add_files' => 'erp.manager.clients.addFiles',
                'clients_delete_file' => 'erp.manager.clients.deleteFile',
                'clients_add_comment' => 'erp.manager.clients.addComment',
                'clients_create' => 'erp.manager.clients.create',
                'clients_search' => 'erp.manager.clients.search',
                'clients_delete' => 'erp.manager.clients.delete',

                'finances_search' => 'erp.manager.finances.search',
                'finances_index' => 'erp.manager.finances.index',

                'tasks_store_kanban' => 'erp.manager.tasks.storeKanban',
                'tasks_store_kanban_task' => 'erp.manager.tasks.storeKanbanTask',
                'tasks_index' => 'erp.manager.tasks.index',
                'tasks_update' => 'erp.manager.tasks.update',
                'tasks_store' => 'erp.manager.tasks.store',
                'tasks_update_kanban' => 'erp.manager.tasks.updateKanban',
                'tasks_update_kanban_task' => 'erp.manager.tasks.updateKanbanTask',
                'tasks_delete_kanban' => 'erp.manager.tasks.deleteKanban',
                'tasks_delete_kanban_task' => 'erp.manager.tasks.deleteKanbanTask',
                'tasks_remove' => 'erp.manager.tasks.remove',
                'tasks_update_task_column' => 'erp.manager.tasks.updateTaskColumn',
                'tasks_search' =>'erp.manager.tasks.search',


                'emails_index' => 'erp.manager.emails.index',
                'emails_send_emails' => 'erp.manager.emails.sendEmails',
                'emails_deleted_emails' => 'erp.manager.emails.deletedEmails',
                'emails_new_mail' => 'erp.manager.emails.newMail',
                'emails_delete_email' => 'erp.manager.emails.deleteEmail',
                'emails_get_mails' => 'erp.manager.emails.getMails',
                'emails_open_email' => 'erp.manager.emails.openEmail',
                'emails_send_email' => 'erp.manager.emails.sendMail',
                'emails_force_delete_emails' => 'erp.manager.emails.forceDeleteEmails',
                'emails_restore_email' => 'erp.manager.emails.restoreEmail',
                'emails_open_send_email' => 'erp.manager.emails.openSendEmail',
                'emails_search' => 'erp.manager.emails.search',
                'emails_send_search' => 'erp.manager.emails.sendEmailsSearch',

                'messages_show_chat' => 'erp.manager.messages.showChat',
                'messages_index' => 'erp.manager.messages.index',
                'messages_update_notifications' => 'erp.manager.messages.updateNavbarNotifications',
                'messages_search_users' => 'erp.manager.messages.searchUsers',
                'messages_search'=>'erp.manager.messages.search',
                'messages_delete_chat' => 'erp.manager.messages.deleteChat',
                'messages_add_user' => 'erp.manager.messages.addUser',
                'messages_store_chat_message' => 'erp.manager.messages.storeChatMessage',
                'messages_update_message'=>'erp.manager.messages.updateMessage',
                'messages_update_chat_message'=> 'erp.manager.messages.updateChatMessage',
                'messages_delete_message' => 'erp.manager.messages.deleteMessage',
                'messages_delete_chat_message' => 'erp.manager.messages.deleteChatMessage',
                'messages_show_private_chat' => 'erp.manager.messages.showPrivatChat',
                'messages_store_private_message' => 'erp.manager.messages.storePrivatMessage',
                'messages_read_message' => 'erp.manager.messages.readMessage',
                'messages_store_chat' => 'erp.manager.messages.storeChat',
                'messages_store_message' => 'erp.manager.messages.storeMessage',
                'messages_chat_reply' => 'erp.manager.messages.chatReply',
                'messages_message_reply' => 'erp.manager.messages.messageReply',
                'messages_update_chat' => 'erp.manager.messages.updateChat',

                'articles_index' => 'erp.manager.articles.index',
                'articles_show_article' => 'erp.manager.articles.showArticle',
                'articles_store_article' => 'erp.manager.articles.storeArticle',
                'articles_add_to_favorites' => 'erp.manager.articles.addToFavorites',
                'articles_edit' => 'erp.manager.articles.edit',
                'articles_delete' => 'erp.manager.articles.delete',
                'articles_update_article' => 'erp.manager.articles.updateArticle',
                'articles_search' => 'erp.manager.articles.search',

            ],

            'executive' => [
                'order_store' => 'erp.executive.orders.store',
                'order_create' => 'erp.executive.orders.create',
                'order_search' => 'erp.executive.orders.search',
                'order_index' => 'erp.executive.orders.index',
                'update' => 'erp.executive.orders.update',
                'order_edit' => 'erp.executive.orders.edit',
                'order_delete' => 'erp.executive.orders.delete',
                'order_cancellation' => 'erp.executive.orders.cancellation',
                'order_return' => 'erp.executive.orders.return',
                'order_add_mover' => 'erp.executive.orders.addMover',
                'orders_to_bank_operations' => 'erp.executive.orders.toBankOperations',
                'orders_addFiles' => 'erp.executive.orders.addFiles',
                'orders_deleteFile' => 'erp.executive.orders.deleteFile',
                'toBankOperations' => 'erp.executive.orders.toBankOperations',
                'orders_addComment' => 'erp.executive.orders.addComment',

                'leads_index' => 'erp.executive.leads.index',
                'leads_search' => 'erp.executive.leads.search',
                'leads_to_order' => 'erp.executive.leads.toOrder',
//                'leads_delete' => 'erp.executive.leads.delete',
                'leads_delete' => 'erp.executive.leads.destroy',
                'leads_update' => 'erp.executive.leads.update',
                'leads_store' => 'erp.executive.leads.store',
                'leads_delete_file' => 'erp.executive.leads.deleteFile',

                'employee_index' => 'erp.executive.employees.index',
                'employee_edit' => 'erp.executive.employees.edit',
                'employee_store' => 'erp.executive.employees.store',
                'employee_create' => 'erp.executive.employees.create',
                'employee_search' => 'erp.executive.employees.search',
                'employee_update' => 'erp.executive.employees.update',
                'employee_delete' => 'erp.executive.employees.delete',
                'employee_delete_file' => 'erp.executive.employees.deleteEmployeeDocument',

                'movers_index' => 'erp.executive.movers.index',
                'movers_planning' => 'erp.executive.movers.planning',
                'movers_planning_search' => 'erp.executive.movers.planningSearch',
                'movers_edit' => 'erp.executive.movers.edit',
                'movers_create' => 'erp.executive.movers.create',
                'movers_store' => 'erp.executive.movers.store',
                'movers_update' => 'erp.executive.movers.update',
                'movers_add_photo' => 'erp.executive.movers.addPhoto',
                'movers_search' => 'erp.executive.movers.search',
                'movers_delete' => 'erp.executive.movers.delete',
                'movers_add_bonus' => 'erp.executive.movers.addBonus',
                'movers_pay_to_mover' => 'erp.executive.movers.payToMover',

                'applicants_index' => 'erp.executive.applicants.index',
                'applicants_edit' => 'erp.executive.applicants.edit',
                'applicants_store' => 'erp.executive.applicants.store',
                'applicants_search' => 'erp.executive.applicants.search',
                'applicants_create' => 'erp.executive.applicants.create',
                'applicants_update' => 'erp.executive.applicants.update',
                'applicants_delete_file' => 'erp.executive.applicants.deleteApplicantDocument',
                'applicants_delete' => 'erp.executive.applicants.delete',
                'applicants_remove_to_interviewee' => 'erp.executive.applicants.removeToInterviewee',

                'arrears_search' => 'erp.executive.arrears.search',
                'arrears_index' => 'erp.executive.arrears.index',

                'interviewees_index' => 'erp.executive.interviewees.index',
                'interviewees_edit' => 'erp.executive.interviewees.edit',
                'interviewees_update' => 'erp.executive.interviewees.update',
                'interviewees_add_documents' => 'erp.executive.interviewees.add_documents',
                'interviewees_add_photo' => 'erp.executive.interviewees.addPhoto',
                'interviewees_search' => 'erp.executive.interviewees.search',
                'interviewees_remove_to_employees' => 'erp.executive.interviewees.removeToEmployees',
                'interviewees_delete' => 'erp.executive.interviewees.delete',
                'interviewees_delete_file'=> 'erp.executive.interviewees.deleteFile',


                'client_create' => 'erp.executive.clients.create',
                'clients_index' => 'erp.executive.clients.index',
                'clients_edit' => 'erp.executive.clients.edit',
                'clients_contact_delete' => 'erp.executive.clients.client_delete',
                'clients_store' => 'erp.executive.clients.store',
                'clients_update' => 'erp.executive.clients.update',
                'clients_add_files' => 'erp.executive.clients.addFiles',
                'clients_delete_file' => 'erp.executive.clients.deleteFile',
                'clients_add_comment' => 'erp.executive.clients.addComment',
                'clients_create' => 'erp.executive.clients.create',
                'clients_search' => 'erp.executive.clients.search',
                'clients_delete' => 'erp.executive.clients.delete',

                'finances_search' => 'erp.executive.finances.search',
                'finances_index' => 'erp.executive.finances.index',

                'tasks_store_kanban' => 'erp.executive.tasks.storeKanban',
                'tasks_store_kanban_task' => 'erp.executive.tasks.storeKanbanTask',
                'tasks_index' => 'erp.executive.tasks.index',
                'tasks_update' => 'erp.executive.tasks.update',
                'tasks_store' => 'erp.executive.tasks.store',
                'tasks_update_kanban' => 'erp.executive.tasks.updateKanban',
                'tasks_update_kanban_task' => 'erp.executive.tasks.updateKanbanTask',
                'tasks_delete_kanban' => 'erp.executive.tasks.deleteKanban',
                'tasks_delete_kanban_task' => 'erp.executive.tasks.deleteKanbanTask',
                'tasks_remove' => 'erp.executive.tasks.remove',
                'tasks_update_task_column' => 'erp.executive.tasks.updateTaskColumn',
                'tasks_search' =>'erp.executive.tasks.search',

                'emails_index' => 'erp.executive.emails.index',
                'emails_send_emails' => 'erp.executive.emails.sendEmails',
                'emails_deleted_emails' => 'erp.executive.emails.deletedEmails',
                'emails_new_mail' => 'erp.executive.emails.newMail',
                'emails_delete_email' => 'erp.executive.emails.deleteEmail',
                'emails_get_mails' => 'erp.executive.emails.getMails',
                'emails_open_email' => 'erp.executive.emails.openEmail',
                'emails_send_email' => 'erp.executive.emails.sendMail',
                'emails_force_delete_emails' => 'erp.executive.emails.forceDeleteEmails',
                'emails_restore_email' => 'erp.executive.emails.restoreEmail',
                'emails_open_send_email' => 'erp.executive.emails.openSendEmail',
                'emails_search' => 'erp.executive.emails.search',
                'emails_send_search' => 'erp.executive.emails.sendEmailsSearch',

                'messages_show_chat' => 'erp.executive.messages.showChat',
                'messages_index' => 'erp.executive.messages.index',
                'messages_search'=>'erp.executive.messages.search',
                'messages_update_notifications' => 'erp.executive.messages.updateNavbarNotifications',
                'messages_search_users' => 'erp.executive.messages.searchUsers',
                'messages_delete_chat' => 'erp.executive.messages.deleteChat',
                'messages_add_user' => 'erp.executive.messages.addUser',
                'messages_store_chat_message' => 'erp.executive.messages.storeChatMessage',
                'messages_update_message'=>'erp.executive.messages.updateMessage',
                'messages_update_chat_message'=> 'erp.executive.messages.updateChatMessage',
                'messages_delete_message' => 'erp.executive.messages.deleteMessage',
                'messages_delete_chat_message' => 'erp.executive.messages.deleteChatMessage',
                'messages_show_private_chat' => 'erp.executive.messages.showPrivatChat',
                'messages_store_private_message' => 'erp.executive.messages.storePrivatMessage',
                'messages_read_message' => 'erp.executive.messages.readMessage',
                'messages_store_chat' => 'erp.executive.messages.storeChat',
                'messages_store_message' => 'erp.executive.messages.storeMessage',
                'messages_chat_reply' => 'erp.executive.messages.chatReply',
                'messages_message_reply' => 'erp.executive.messages.messageReply',
                'messages_update_chat' => 'erp.executive.messages.updateChat',

                'articles_index' => 'erp.executive.articles.index',
                'articles_show_article' => 'erp.executive.articles.showArticle',
                'articles_store_article' => 'erp.executive.articles.storeArticle',
                'articles_add_to_favorites' => 'erp.executive.articles.addToFavorites',
                'articles_edit' => 'erp.executive.articles.edit',
                'articles_delete' => 'erp.executive.articles.delete',
                'articles_update_article' => 'erp.executive.articles.updateArticle',
                'articles_search' => 'erp.executive.articles.search',
            ],

            'logist' => [
                'store' => 'erp.logist.orders.store',
                'order_create' => 'erp.logist.orders.create',
                'order_search' => 'erp.logist.orders.search',
                'order_index' => 'erp.logist.orders.index',
                'orders_addComment' => 'erp.logist.orders.addComment',
                'order_add_mover' => 'erp.logist.orders.addMover',

                'movers_index' => 'erp.logist.movers.index',
                'movers_planning' => 'erp.logist.movers.planning',
                'movers_planning_search' => 'erp.logist.movers.planningSearch',
                'movers_edit' => 'erp.logist.movers.edit',
                'movers_create' => 'erp.logist.movers.create',
                'movers_store' => 'erp.logist.movers.store',
                'movers_update' => 'erp.logist.movers.update',
                'movers_add_photo' => 'erp.logist.movers.addPhoto',
                'movers_search' => 'erp.logist.movers.search',
                'movers_delete' => 'erp.logist.movers.delete',
                'movers_add_bonus' => 'erp.logist.movers.addBonus',
                'movers_pay_to_mover' => 'erp.logist.movers.payToMover',

                'tasks_store_kanban' => 'erp.logist.tasks.storeKanban',
                'tasks_store_kanban_task' => 'erp.logist.tasks.storeKanbanTask',
                'tasks_index' => 'erp.logist.tasks.index',
                'tasks_update' => 'erp.logist.tasks.update',
                'tasks_store' => 'erp.logist.tasks.store',
                'tasks_update_kanban' => 'erp.logist.tasks.updateKanban',
                'tasks_update_kanban_task' => 'erp.logist.tasks.updateKanbanTask',
                'tasks_delete_kanban' => 'erp.logist.tasks.deleteKanban',
                'tasks_delete_kanban_task' => 'erp.logist.tasks.deleteKanbanTask',
                'tasks_remove' => 'erp.logist.tasks.remove',
                'tasks_update_task_column' => 'erp.logist.tasks.updateTaskColumn',
                'tasks_search' =>'erp.logist.tasks.search',


                'emails_index' => 'erp.logist.emails.index',
                'emails_send_emails' => 'erp.logist.emails.sendEmails',
                'emails_deleted_emails' => 'erp.logist.emails.deletedEmails',
                'emails_new_mail' => 'erp.logist.emails.newMail',
                'emails_delete_email' => 'erp.logist.emails.deleteEmail',
                'emails_get_mails' => 'erp.logist.emails.getMails',
                'emails_open_email' => 'erp.logist.emails.openEmail',
                'emails_send_email' => 'erp.logist.emails.sendMail',
                'emails_force_delete_emails' => 'erp.logist.emails.forceDeleteEmails',
                'emails_restore_email' => 'erp.logist.emails.restoreEmail',
                'emails_open_send_email' => 'erp.logist.emails.openSendEmail',
                'emails_search' => 'erp.logist.emails.search',
                'emails_send_search' => 'erp.logist.emails.sendEmailsSearch',

                'messages_show_chat' => 'erp.logist.messages.showChat',
                'messages_index' => 'erp.logist.messages.index',
                'messages_update_notifications' => 'erp.logist.messages.updateNavbarNotifications',
                'messages_search_users' => 'erp.logist.messages.searchUsers',
                'messages_search'=>'erp.logist.messages.search',
                'messages_delete_chat' => 'erp.logist.messages.deleteChat',
                'messages_add_user' => 'erp.logist.messages.addUser',
                'messages_store_chat_message' => 'erp.logist.messages.storeChatMessage',
                'messages_update_message'=>'erp.logist.messages.updateMessage',
                'messages_update_chat_message'=> 'erp.logist.messages.updateChatMessage',
                'messages_delete_message' => 'erp.logist.messages.deleteMessage',
                'messages_delete_chat_message' => 'erp.logist.messages.deleteChatMessage',
                'messages_show_private_chat' => 'erp.logist.messages.showPrivatChat',
                'messages_store_private_message' => 'erp.logist.messages.storePrivatMessage',
                'messages_read_message' => 'erp.logist.messages.readMessage',
                'messages_store_chat' => 'erp.logist.messages.storeChat',
                'messages_store_message' => 'erp.logist.messages.storeMessage',
                'messages_chat_reply' => 'erp.logist.messages.chatReply',
                'messages_message_reply' => 'erp.logist.messages.messageReply',
                'messages_update_chat' => 'erp.logist.messages.updateChat',

                'articles_index' => 'erp.logist.articles.index',
                'articles_show_article' => 'erp.logist.articles.showArticle',
                'articles_store_article' => 'erp.logist.articles.storeArticle',
                'articles_add_to_favorites' => 'erp.logist.articles.addToFavorites',
                'articles_edit' => 'erp.logist.articles.edit',
                'articles_delete' => 'erp.logist.articles.delete',
                'articles_update_article' => 'erp.logist.articles.updateArticle',
                'articles_search' => 'erp.logist.articles.search',

            ],

            'accountant' => [
                'order_edit' => 'erp.accountant.orders.edit',
                'order_index' => 'erp.accountant.orders.index',
                'orders_addComment' => 'erp.accountant.orders.addComment',
                'orders_to_bank_operations' => 'erp.accountant.orders.toBankOperations',

                'arrears_search' => 'erp.accountant.arrears.search',
                'arrears_index' => 'erp.accountant.arrears.index',

                'clients_index' => 'erp.accountant.clients.index',
                'clients_edit' => 'erp.accountant.clients.edit',
                'clients_contact_delete' => 'erp.accountant.clients.client_delete',
                'clients_store' => 'erp.accountant.clients.store',
                'clients_update' => 'erp.accountant.clients.update',
                'clients_add_files' => 'erp.accountant.clients.addFiles',
                'clients_delete_file' => 'erp.accountant.clients.deleteFile',
                'clients_add_comment' => 'erp.accountant.clients.addComment',
                'clients_create' => 'erp.accountant.clients.create',
                'clients_search' => 'erp.accountant.clients.search',
                'clients_delete' => 'erp.accountant.clients.delete',

                'finances_search' => 'erp.accountant.finances.search',
                'finances_index' => 'erp.accountant.finances.index',

                'tasks_store_kanban' => 'erp.accountant.tasks.storeKanban',
                'tasks_store_kanban_task' => 'erp.accountant.tasks.storeKanbanTask',
                'tasks_index' => 'erp.accountant.tasks.index',
                'tasks_update' => 'erp.accountant.tasks.update',
                'tasks_store' => 'erp.accountant.tasks.store',
                'tasks_update_kanban' => 'erp.accountant.tasks.updateKanban',
                'tasks_update_kanban_task' => 'erp.accountant.tasks.updateKanbanTask',
                'tasks_delete_kanban' => 'erp.accountant.tasks.deleteKanban',
                'tasks_delete_kanban_task' => 'erp.accountant.tasks.deleteKanbanTask',
                'tasks_remove' => 'erp.accountant.tasks.remove',
                'tasks_update_task_column' => 'erp.accountant.tasks.updateTaskColumn',
                'tasks_search' =>'erp.accountant.tasks.search',


                'emails_index' => 'erp.accountant.emails.index',
                'emails_send_emails' => 'erp.accountant.emails.sendEmails',
                'emails_deleted_emails' => 'erp.accountant.emails.deletedEmails',
                'emails_new_mail' => 'erp.accountant.emails.newMail',
                'emails_delete_email' => 'erp.accountant.emails.deleteEmail',
                'emails_get_mails' => 'erp.accountant.emails.getMails',
                'emails_open_email' => 'erp.accountant.emails.openEmail',
                'emails_send_email' => 'erp.accountant.emails.sendMail',
                'emails_force_delete_emails' => 'erp.accountant.emails.forceDeleteEmails',
                'emails_restore_email' => 'erp.accountant.emails.restoreEmail',
                'emails_open_send_email' => 'erp.accountant.emails.openSendEmail',
                'emails_search' => 'erp.accountant.emails.search',
                'emails_send_search' => 'erp.accountant.emails.sendEmailsSearch',

                'messages_show_chat' => 'erp.accountant.messages.showChat',
                'messages_index' => 'erp.accountant.messages.index',
                'messages_update_notifications' => 'erp.accountant.messages.updateNavbarNotifications',
                'messages_search_users' => 'erp.accountant.messages.searchUsers',
                'messages_search'=>'erp.accountant.messages.search',
                'messages_delete_chat' => 'erp.accountant.messages.deleteChat',
                'messages_add_user' => 'erp.accountant.messages.addUser',
                'messages_store_chat_message' => 'erp.accountant.messages.storeChatMessage',
                'messages_update_message'=>'erp.accountant.messages.updateMessage',
                'messages_update_chat_message'=> 'erp.accountant.messages.updateChatMessage',
                'messages_delete_message' => 'erp.accountant.messages.deleteMessage',
                'messages_delete_chat_message' => 'erp.accountant.messages.deleteChatMessage',
                'messages_show_private_chat' => 'erp.accountant.messages.showPrivatChat',
                'messages_store_private_message' => 'erp.accountant.messages.storePrivatMessage',
                'messages_read_message' => 'erp.accountant.messages.readMessage',
                'messages_store_chat' => 'erp.accountant.messages.storeChat',
                'messages_store_message' => 'erp.accountant.messages.storeMessage',
                'messages_chat_reply' => 'erp.accountant.messages.chatReply',
                'messages_message_reply' => 'erp.accountant.messages.messageReply',
                'messages_update_chat' => 'erp.accountant.messages.updateChat',

                'articles_index' => 'erp.accountant.articles.index',
                'articles_show_article' => 'erp.accountant.articles.showArticle',
                'articles_store_article' => 'erp.accountant.articles.storeArticle',
                'articles_add_to_favorites' => 'erp.accountant.articles.addToFavorites',
                'articles_edit' => 'erp.accountant.articles.edit',
                'articles_delete' => 'erp.accountant.articles.delete',
                'articles_update_article' => 'erp.accountant.articles.updateArticle',
                'articles_search' => 'erp.accountant.articles.search',

            ],

            'hr' => [

                'applicants_index' => 'erp.hr.applicants.index',
                'applicants_edit' => 'erp.hr.applicants.edit',
                'applicants_store' => 'erp.hr.applicants.store',
                'applicants_create' => 'erp.hr.applicants.create',
                'applicants_search' => 'erp.hr.applicants.search',
                'applicants_update' => 'erp.hr.applicants.update',
                'applicants_delete' => 'erp.hr.applicants.delete',
                'applicants_delete_file' => 'erp.hr.applicants.deleteApplicantDocument',
                'applicants_remove_to_interviewee' => 'erp.hr.applicants.removeToInterviewee',

                'interviewees_index' => 'erp.hr.interviewees.index',
                'interviewees_edit' => 'erp.hr.interviewees.edit',
                'interviewees_update' => 'erp.hr.interviewees.update',
                'interviewees_add_documents' => 'erp.hr.interviewees.add_documents',
                'interviewees_add_photo' => 'erp.hr.interviewees.addPhoto',
                'interviewees_search' => 'erp.hr.interviewees.search',
                'interviewees_remove_to_employees' => 'erp.hr.interviewees.removeToEmployees',
                'interviewees_delete' => 'erp.hr.interviewees.delete',
                'interviewees_delete_file'=> 'erp.hr.interviewees.deleteFile',

                'tasks_store_kanban' => 'erp.hr.tasks.storeKanban',
                'tasks_store_kanban_task' => 'erp.hr.tasks.storeKanbanTask',
                'tasks_index' => 'erp.hr.tasks.index',
                'tasks_update' => 'erp.hr.tasks.update',
                'tasks_store' => 'erp.hr.tasks.store',
                'tasks_update_kanban' => 'erp.hr.tasks.updateKanban',
                'tasks_update_kanban_task' => 'erp.hr.tasks.updateKanbanTask',
                'tasks_delete_kanban' => 'erp.hr.tasks.deleteKanban',
                'tasks_delete_kanban_task' => 'erp.hr.tasks.deleteKanbanTask',
                'tasks_remove' => 'erp.hr.tasks.remove',
                'tasks_update_task_column' => 'erp.hr.tasks.updateTaskColumn',
                'tasks_search' =>'erp.hr.tasks.search',

                'emails_index' => 'erp.hr.emails.index',
                'emails_send_emails' => 'erp.hr.emails.sendEmails',
                'emails_deleted_emails' => 'erp.hr.emails.deletedEmails',
                'emails_new_mail' => 'erp.hr.emails.newMail',
                'emails_delete_email' => 'erp.hr.emails.deleteEmail',
                'emails_get_mails' => 'erp.hr.emails.getMails',
                'emails_open_email' => 'erp.hr.emails.openEmail',
                'emails_send_email' => 'erp.hr.emails.sendMail',
                'emails_force_delete_emails' => 'erp.hr.emails.forceDeleteEmails',
                'emails_restore_email' => 'erp.hr.emails.restoreEmail',
                'emails_open_send_email' => 'erp.hr.emails.openSendEmail',
                'emails_search' => 'erp.hr.emails.search',
                'emails_send_search' => 'erp.hr.emails.sendEmailsSearch',

                'messages_show_chat' => 'erp.hr.messages.showChat',
                'messages_index' => 'erp.hr.messages.index',
                'messages_update_notifications' => 'erp.hr.messages.updateNavbarNotifications',
                'messages_search_users' => 'erp.hr.messages.searchUsers',
                'messages_search'=>'erp.hr.messages.search',
                'messages_delete_chat' => 'erp.hr.messages.deleteChat',
                'messages_add_user' => 'erp.hr.messages.addUser',
                'messages_store_chat_message' => 'erp.hr.messages.storeChatMessage',
                'messages_update_message'=>'erp.hr.messages.updateMessage',
                'messages_update_chat_message'=> 'erp.hr.messages.updateChatMessage',
                'messages_delete_message' => 'erp.hr.messages.deleteMessage',
                'messages_delete_chat_message' => 'erp.hr.messages.deleteChatMessage',
                'messages_show_private_chat' => 'erp.hr.messages.showPrivatChat',
                'messages_store_private_message' => 'erp.hr.messages.storePrivatMessage',
                'messages_read_message' => 'erp.hr.messages.readMessage',
                'messages_store_chat' => 'erp.hr.messages.storeChat',
                'messages_store_message' => 'erp.hr.messages.storeMessage',
                'messages_chat_reply' => 'erp.hr.messages.chatReply',
                'messages_message_reply' => 'erp.hr.messages.messageReply',
                'messages_update_chat' => 'erp.hr.messages.updateChat',

                'articles_index' => 'erp.hr.articles.index',
                'articles_show_article' => 'erp.hr.articles.showArticle',
                'articles_store_article' => 'erp.hr.articles.storeArticle',
                'articles_add_to_favorites' => 'erp.hr.articles.addToFavorites',
                'articles_edit' => 'erp.hr.articles.edit',
                'articles_delete' => 'erp.hr.articles.delete',
                'articles_update_article' => 'erp.hr.articles.updateArticle',
                'articles_search' => 'erp.hr.articles.search',

            ],
        ];

        if ($user->is_manager) {
            $currentRole = 'manager';
        } elseif ($user->is_executive) {
            $currentRole = 'executive';
        } elseif ($user->is_logist) {
            $currentRole = 'logist';
        } elseif ($user->is_accountant) {
            $currentRole = 'accountant';
        } elseif ($user->is_hr) {
            $currentRole = 'hr';
        } elseif ($user->is_admin) {
            $currentRole = 'admin';
        } else {
            abort(403, 'Unauthorized');
        }

        return [
            'currentRole' => $currentRole,
            'roleData' => $roles[$currentRole],
        ];
    }

}


